version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: "go run benny"
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - db
      - dragonfly

  db:
    image: edgedb/edgedb:2.1
    restart: always
    environment:
      - EDGEDB_SERVER_ADMIN_UI=enabled
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5656"
    volumes:
      - ./dbschema:/dbschema
      - ./credentials:/root/.config/edgedb/credentials
      - ./volumes/edgedb_data:/var/lib/edgedb/data

  dragonfly:
    build:
      context: .
      dockerfile: dragonfly.Dockerfile
    restart: always
    ulimits:
      memlock: -1
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - dragonflydata:/data

volumes:
  dragonflydata: